In [1]:
import pandas as pd, ast
from collections import defaultdict

dir_path = '/home/alaysia/.cache/huggingface/hub/datasets--tahoebio--EmeraldBay/snapshots/f2a0be6b02f731553657f0115c345b20bb020ede'
summary_stats_df = pd.read_parquet(dir_path + '/metadata/summary_statistics.parquet')
cell_line_md_df = pd.read_parquet(dir_path + '/metadata/cell_line_metadata.parquet')
drug_md_df = pd.read_parquet(dir_path + '/metadata/drug_metadata.parquet')
gene_md_df = pd.read_parquet(dir_path + '/metadata/gene_metadata.parquet')

# Raw Tables

In [6]:
summary_stats_df

,cell_line,condition,growth_rate
0,CVCL_0023,"[('DMSO_T0', 0.0, 'uM')]",-0.036039
1,CVCL_0218,"[('DMSO_T0', 0.0, 'uM')]",1.689574
2,CVCL_0320,"[('DMSO_T0', 0.0, 'uM')]",-1.872728
3,CVCL_0546,"[('DMSO_T0', 0.0, 'uM')]",-2.123235
4,CVCL_0332,"[('DMSO_T0', 0.0, 'uM')]",1.247865
...,...,...,...
4987,CVCL_1547,"[('LY3200882', 0.1, 'uM'), ('Adagrasib', 0.005...",0.517212
4988,CVCL_1495,"[('LY3200882', 0.1, 'uM'), ('Adagrasib', 0.005...",-0.996782
4989,CVCL_1531,"[('LY3200882', 0.1, 'uM'), ('Adagrasib', 0.005...",-0.584484
4990,CVCL_1517,"[('LY3200882', 0.1, 'uM'), ('Adagrasib', 0.005...",-0.186512
4991,CVCL_1381,"[('LY3200882', 0.1, 'uM'), ('Adagrasib', 0.005...",0.549793

In [5]:
cell_line_md_df

,cell_name,Cell_ID_DepMap,Cell_ID_Cellosaur,Organ,Driver_Gene_Symbol,Driver_VarZyg,Driver_VarType,Driver_ProtEffect_or_CdnaEffect,Driver_Mech_InferDM,Driver_GeneType_DM
0,A549,ACH-000681,CVCL_0023,Lung,CDKN2A,Hom,Deletion,DEL,LoF,Suppressor
1,A549,ACH-000681,CVCL_0023,Lung,CDKN2B,Hom,Deletion,DEL,LoF,Suppressor
2,A549,ACH-000681,CVCL_0023,Lung,KRAS,Hom,Missense,p.G12S,GoF,Oncogene
3,A549,ACH-000681,CVCL_0023,Lung,SMARCA4,Hom,Frameshift,p.Q729fs,LoF,Suppressor
4,A549,ACH-000681,CVCL_0023,Lung,STK11,Hom,Stopgain,p.Q37*,LoF,Suppressor
...,...,...,...,...,...,...,...,...,...,...
482,LOX-IMVI,ACH-000750,CVCL_1381,Skin,ARID1A,Het,Stopgain,p.Q1212*,LoF,Suppressor
483,LOX-IMVI,ACH-000750,CVCL_1381,Skin,BRAF,Het,Missense,p.V600E,GoF,Oncogene
484,LOX-IMVI,ACH-000750,CVCL_1381,Skin,CDKN2A,Hom,Deletion,DEL,LoF,Suppressor
485,LOX-IMVI,ACH-000750,CVCL_1381,Skin,NF1,Het,Stopgain,p.Q1174*,LoF,Suppressor
486,LOX-IMVI,ACH-000750,CVCL_1381,Skin,TERT,NaN,Promoter,1-124C>T,GoF,Oncogene

In [7]:
drug_md_df

,drug,targets,mutations,moa-broad,moa-fine,human-use,clinical-trials,claude-notes-approval,pubchem-cid,canonical-smiles
0,Adagrasib,KRAS,KRASG12C,inhibitor/antagonist,RAS inhibitor,yes,yes,"Adagrasib (Krazati), a KRAS G12C inhibitor, ga...",138611145.0,CN1CCCC1COC2=NC3=C(CCN(C3)C4=CC=CC5=C4C(=CC=C5...
1,Capecitabine,TYMP,NaN,inhibitor/antagonist,DNA synthesis/repair inhibitor,yes,yes,"Approved oral chemo (Xeloda), first FDA-approv...",60953.0,CCCCCOC(=O)NC1=NC(=O)N(C=C1F)C2C(C(C(O2)C)O)O
2,Cetuximab,EGFR,NaN,inhibitor/antagonist,EGFR/ERBB inhibitor,yes,yes,"Anti-EGFR monoclonal antibody (Erbitux), FDA a...",NaN,NaN
3,Dabrafenib,"BRAF, RAF1",BRAFV600E,inhibitor/antagonist,RAF inhibitor,yes,yes,BRAF kinase inhibitor (Tafinlar); FDA-approved...,44462760.0,CC(C)(C)C1=NC(=C(S1)C2=NC(=NC=C2)N)C3=C(C(=CC=...
4,Encorafenib,BRAF,BRAFV600E,inhibitor/antagonist,RAF inhibitor,yes,yes,BRAF inhibitor (Braftovi); FDA-approved June 2...,50922675.0,CC(C)N1C=C(C(=N1)C2=C(C(=CC(=C2)Cl)NS(=O)(=O)C...
5,Fluorouracil,TYMS,NaN,inhibitor/antagonist,DNA synthesis/repair inhibitor,yes,yes,FDA-approved antimetabolite chemotherapy (5-FU...,3385.0,C1=C(C(=O)NC(=O)N1)F
6,GDC-6036,KRAS,KRASG12C,inhibitor/antagonist,RAS inhibitor,no,yes,"GDC-6036 (divarasib), Genentech/Roche covalent...",146624881.0,CC1CN(CCN1C2=NC(=NC3=C(C(=C(C=C32)Cl)C4=C(C(=C...
7,Galunisertib,TGFBR1,NaN,inhibitor/antagonist,Other TK inhibitor,no,yes,TGF-β receptor I inhibitor (LY2157299). Invest...,10090485.0,CC1=NC(=CC=C1)C2=NN3CCCC3=C2C4=C5C=C(C=CC5=NC=...
8,Gemcitabine,none,NaN,inhibitor/antagonist,DNA synthesis/repair inhibitor,yes,yes,Chemotherapy (Gemzar); FDA-approved 1996 pancr...,60750.0,C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)(F)F
9,Irinotecan,TOP1,NaN,inhibitor/antagonist,DNA synthesis/repair inhibitor,yes,yes,Topoisomerase I inhibitor; FDA accelerated app...,60838.0,CCC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC)O)C2=NC5=...
10,LY3200882,TGFBR1,NaN,inhibitor/antagonist,Other TK inhibitor,no,yes,Eli Lilly investigational TGFβ receptor 1 inhi...,121249291.0,CC(C)(C1=NC=CC(=C1)NC2=NC=CC(=C2)OC3=CN(N=C3C4...
11,Lapatinib ditosylate,"EGFR, ERBB2",NaN,inhibitor/antagonist,EGFR/ERBB inhibitor,yes,yes,FDA-approved 2007 as Tykerb/Tyverb (lapatinib ...,11557040.0,CC1=CC=C(C=C1)S(=O)(=O)O.CC1=CC=C(C=C1)S(=O)(=...
12,Leucovorin,none,NaN,unclear,DNA synthesis/repair inhibitor,yes,yes,Folinic acid; long FDA-approved for methotrexa...,135403648.0,C1C(N(C2=C(N1)N=C(NC2=O)N)C=O)CNC3=CC=C(C=C3)C...
13,Oxaliplatin,none,NaN,inhibitor/antagonist,DNA synthesis/repair inhibitor,yes,yes,"FDA-approved platinum chemotherapy (Eloxatin),...",9887053.0,C1CCC(C(C1)[NH-])[NH-].C(=O)(C(=O)O)O.[Pt+2]
14,PF-06952229,TGFBR1,NaN,inhibitor/antagonist,Other TK inhibitor,no,yes,Pfizer TGF-β-R1 inhibitor (MDV6058). Phase I i...,118211239.0,CC(C)C1=CN=C(C=C1NC2=C(C=NC=C2)C(=O)NC(CO)CO)C...
15,Paclitaxel,TUBB1,NaN,unclear,Microtubule inhibitor,yes,yes,FDA-approved 1992 (Taxol); taxane chemotherapy...,36314.0,CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)...
16,Panitumumab,EGFR,NaN,inhibitor/antagonist,EGFR/ERBB inhibitor,yes,yes,Fully human anti-EGFR monoclonal antibody (Vec...,NaN,NaN
17,Pertuzumab,ERBB2,NaN,inhibitor/antagonist,EGFR/ERBB inhibitor,yes,yes,"HER2-targeted monoclonal antibody (Perjeta), F...",NaN,NaN
18,RMC-6236,"HRAS, KRAS, NRAS",KRASG12D,inhibitor/antagonist,RAS inhibitor,no,yes,"Daraxonrasib, investigational oral RAS(ON) mul...",164726578.0,CCN1C2=C3C=C(C=C2)C4=CSC(=N4)CC(C(=O)N5CCCC(N5...
19,Regorafenib,"KDR,KIT,PDGFRB,RET,FLT1,FLT4,RAF1,BRAF,TEK",BRAFV600E,inhibitor/antagonist,Multi-TK inhibitor,yes,yes,"FDA-approved (Stivarga, Bayer) 2012 for colore...",11167602.0,CNC(=O)C1=NC=CC(=C1)OC2=CC(=C(C=C2)NC(=O)NC3=C...
20,Sotorasib,KRAS,KRASG12C,inhibitor/antagonist,RAS inhibitor,yes,yes,KRAS G12C inhibitor (Lumakras/Amgen). FDA acce...,137278711.0,CC1CN(CCN1C2=NC(=O)N(C3=NC(=C(C=C32)F)C4=C(C=C...
21,Tipiracil,"TYMP,TYMS",NaN,inhibitor/antagonist,DNA synthesis/repair inhibitor,yes,yes,Approved 2015 (FDA) only as combination Lonsur...,6323266.0,C1CC(=N)N(C1)CC2=C(C(=O)NC(=O)N2)Cl
22,Trametinib,"MAP2K1, MAP2K2",NaN,inhibitor/antagonist,MEK inhibitor,yes,yes,"FDA-approved MEK1/2 inhibitor (Mekinist, 2013)...",11707110.0,CC1=C2C(=C(N(C1=O)C)NC3=C(C=C(C=C3)I)F)C(=O)N(...
23,Trastuzumab,ERBB2,NaN,inhibitor/antagonist,EGFR/ERBB inhibitor,yes,yes,Humanized anti-HER2 monoclonal antibody (Herce...,NaN,NaN
24,Trifluridine,TYMS,NaN,inhibitor/antagonist,DNA synthesis/repair inhibitor,yes,yes,"FDA-approved antiviral (ophthalmic Viroptic, 1...",6256.0,C1C(C(OC1N2C=C(C(=O)NC2=O)C(F)(F)F)CO)O
25,Tucatinib,ERBB2,NaN,inhibitor/antagonist,EGFR/ERBB inhibitor,yes,yes,FDA-approved kinase inhibitor (HER2); approved...,51039094.0,CC1=C(C=CC(=C1)NC2=NC=NC3=C2C=C(C=C3)NC4=NC(CO...
26,Vociprotafib,PTPN11,NaN,inhibitor/antagonist,Other MAPK inhibitor,no,yes,Investigational SHP2 inhibitor (Revolution Med...,134182831.0,CC1C(C2(CCN(CC2)C3=NC(=C(N=C3CO)SC4=C(C(=NC=C4...

In [8]:
gene_md_df

      gene_symbol       ensembl_id  token_id
0          TSPAN6  ENSG00000000003         3
1            TNMD  ENSG00000000005         4
2            DPM1  ENSG00000000419         5
3           SCYL3  ENSG00000000457         6
4        C1orf112  ENSG00000000460         7
...           ...              ...       ...
63279  AC012476.1  ENSG00000285396     63282
63280  AC104162.2  ENSG00000285399     63283
63281      SOD2-1  ENSG00000285441     63284
63282    ZNF883-1  ENSG00000285447     63285
63283  AC139491.7  ENSG00000285476     63286

[63284 rows x 3 columns]

# Parsed Views

In [2]:
parse = lambda s: tuple(sorted((n, float(c)) for n, c, _ in ast.literal_eval(s)))
summary_stats_df["parsed"]  = summary_stats_df.condition.map(parse)
summary_stats_df["n_drugs"] = summary_stats_df.parsed.map(len)
summary_stats_df["drugs"]   = summary_stats_df.parsed.map(lambda t: "+".join(n for n, _ in t))
summary_stats_df["doses"]   = summary_stats_df.parsed.map(lambda t: "+".join(f"{c:g}" for _, c in t))

conds = (summary_stats_df.drop_duplicates("condition")
           [["drugs", "doses", "n_drugs", "condition", "parsed"]]
           .sort_values(["n_drugs", "drugs", "doses"])
           .reset_index(drop=True))       # 93 rows

ctrl    = conds.drugs.str.startswith("DMSO")
singles = conds[(conds.n_drugs == 1) & ~ctrl]      # 44
combos  = conds[conds.n_drugs > 1]                 # 47
combos.drugs.nunique()                             # 16 distinct drug sets

# dose ladder per drug given alone
singles.groupby("drugs").doses.apply(lambda s: sorted(s, key=float))

# every (drug, dose) measured as a single agent -- the lookup M1 needs
measured = {t[0] for t in singles.parsed}

In [3]:
singles
# combos

,drugs,doses,n_drugs,condition,parsed
0,Adagrasib,0.005,1,"[('Adagrasib', 0.005, 'uM')]","((Adagrasib, 0.005),)"
1,Adagrasib,0.05,1,"[('Adagrasib', 0.05, 'uM')]","((Adagrasib, 0.05),)"
2,Capecitabine,0.05,1,"[('Capecitabine', 0.05, 'uM')]","((Capecitabine, 0.05),)"
3,Capecitabine,0.5,1,"[('Capecitabine', 0.5, 'uM')]","((Capecitabine, 0.5),)"
4,Capecitabine,5,1,"[('Capecitabine', 5.0, 'uM')]","((Capecitabine, 5.0),)"
5,Cetuximab,0.0068596,1,"[('Cetuximab', 0.0068596, 'uM')]","((Cetuximab, 0.0068596),)"
6,Cetuximab,0.068596,1,"[('Cetuximab', 0.068596, 'uM')]","((Cetuximab, 0.068596),)"
9,Encorafenib,0.01,1,"[('Encorafenib', 0.01, 'uM')]","((Encorafenib, 0.01),)"
10,Encorafenib,0.1,1,"[('Encorafenib', 0.1, 'uM')]","((Encorafenib, 0.1),)"
11,Fluorouracil,1,1,"[('Fluorouracil', 1.0, 'uM')]","((Fluorouracil, 1.0),)"
12,Fluorouracil,25,1,"[('Fluorouracil', 25.0, 'uM')]","((Fluorouracil, 25.0),)"
13,Fluorouracil,5,1,"[('Fluorouracil', 5.0, 'uM')]","((Fluorouracil, 5.0),)"
14,GDC-6036,0.001,1,"[('GDC-6036', 0.001, 'uM')]","((GDC-6036, 0.001),)"
15,GDC-6036,0.01,1,"[('GDC-6036', 0.01, 'uM')]","((GDC-6036, 0.01),)"
16,GDC-6036,0.1,1,"[('GDC-6036', 0.1, 'uM')]","((GDC-6036, 0.1),)"
17,Galunisertib,0.1,1,"[('Galunisertib', 0.1, 'uM')]","((Galunisertib, 0.1),)"
18,Galunisertib,0.5,1,"[('Galunisertib', 0.5, 'uM')]","((Galunisertib, 0.5),)"
19,Gemcitabine,1,1,"[('Gemcitabine', 1.0, 'uM')]","((Gemcitabine, 1.0),)"
20,Gemcitabine,10,1,"[('Gemcitabine', 10.0, 'uM')]","((Gemcitabine, 10.0),)"
21,Irinotecan,25,1,"[('Irinotecan', 25.0, 'uM')]","((Irinotecan, 25.0),)"
22,Irinotecan,5,1,"[('Irinotecan', 5.0, 'uM')]","((Irinotecan, 5.0),)"
23,LY3200882,0.1,1,"[('LY3200882', 0.1, 'uM')]","((LY3200882, 0.1),)"
24,LY3200882,0.5,1,"[('LY3200882', 0.5, 'uM')]","((LY3200882, 0.5),)"
25,Lapatinib ditosylate,0.5,1,"[('Lapatinib ditosylate', 0.5, 'uM')]","((Lapatinib ditosylate, 0.5),)"
26,Lapatinib ditosylate,5,1,"[('Lapatinib ditosylate', 5.0, 'uM')]","((Lapatinib ditosylate, 5.0),)"
27,Oxaliplatin,100,1,"[('Oxaliplatin', 100.0, 'uM')]","((Oxaliplatin, 100.0),)"
28,Oxaliplatin,20,1,"[('Oxaliplatin', 20.0, 'uM')]","((Oxaliplatin, 20.0),)"
29,Oxaliplatin,4,1,"[('Oxaliplatin', 4.0, 'uM')]","((Oxaliplatin, 4.0),)"
30,Paclitaxel,0.05,1,"[('Paclitaxel', 0.05, 'uM')]","((Paclitaxel, 0.05),)"
31,Paclitaxel,0.5,1,"[('Paclitaxel', 0.5, 'uM')]","((Paclitaxel, 0.5),)"
32,Panitumumab,0.00692885,1,"[('Panitumumab', 0.00692885, 'uM')]","((Panitumumab, 0.00692885),)"
33,Panitumumab,0.0692885,1,"[('Panitumumab', 0.0692885, 'uM')]","((Panitumumab, 0.0692885),)"
34,Pertuzumab,0.00067568,1,"[('Pertuzumab', 0.00067568, 'uM')]","((Pertuzumab, 0.00067568),)"
35,Pertuzumab,0.0067568,1,"[('Pertuzumab', 0.0067568, 'uM')]","((Pertuzumab, 0.0067568),)"
36,RMC-6236,0.001,1,"[('RMC-6236', 0.001, 'uM')]","((RMC-6236, 0.001),)"
37,RMC-6236,0.01,1,"[('RMC-6236', 0.01, 'uM')]","((RMC-6236, 0.01),)"
38,RMC-6236,0.1,1,"[('RMC-6236', 0.1, 'uM')]","((RMC-6236, 0.1),)"
39,Regorafenib,2,1,"[('Regorafenib', 2.0, 'uM')]","((Regorafenib, 2.0),)"
40,Regorafenib,7.5,1,"[('Regorafenib', 7.5, 'uM')]","((Regorafenib, 7.5),)"
41,Sotorasib,0.005,1,"[('Sotorasib', 0.005, 'uM')]","((Sotorasib, 0.005),)"
42,Sotorasib,0.05,1,"[('Sotorasib', 0.05, 'uM')]","((Sotorasib, 0.05),)"
43,Vociprotafib,0.001,1,"[('Vociprotafib', 0.001, 'uM')]","((Vociprotafib, 0.001),)"
44,Vociprotafib,0.01,1,"[('Vociprotafib', 0.01, 'uM')]","((Vociprotafib, 0.01),)"
45,Vociprotafib,0.1,1,"[('Vociprotafib', 0.1, 'uM')]","((Vociprotafib, 0.1),)"

## combos

In [5]:
combos

,drugs,doses,n_drugs,condition,parsed
46,Adagrasib+Cetuximab,0.005+0.0068596,2,"[('Adagrasib', 0.005, 'uM'), ('Cetuximab', 0.0...","((Adagrasib, 0.005), (Cetuximab, 0.0068596))"
47,Adagrasib+Cetuximab,0.005+0.068596,2,"[('Cetuximab', 0.068596, 'uM'), ('Adagrasib', ...","((Adagrasib, 0.005), (Cetuximab, 0.068596))"
48,Adagrasib+Cetuximab,0.01+0.068596,2,"[('Adagrasib', 0.01, 'uM'), ('Cetuximab', 0.06...","((Adagrasib, 0.01), (Cetuximab, 0.068596))"
49,Adagrasib+Galunisertib,0.005+0.1,2,"[('Adagrasib', 0.005, 'uM'), ('Galunisertib', ...","((Adagrasib, 0.005), (Galunisertib, 0.1))"
50,Adagrasib+Galunisertib,0.005+0.5,2,"[('Adagrasib', 0.005, 'uM'), ('Galunisertib', ...","((Adagrasib, 0.005), (Galunisertib, 0.5))"
51,Adagrasib+Galunisertib,0.01+0.5,2,"[('Galunisertib', 0.5, 'uM'), ('Adagrasib', 0....","((Adagrasib, 0.01), (Galunisertib, 0.5))"
52,Adagrasib+LY3200882,0.005+0.1,2,"[('LY3200882', 0.1, 'uM'), ('Adagrasib', 0.005...","((Adagrasib, 0.005), (LY3200882, 0.1))"
53,Adagrasib+LY3200882,0.005+0.5,2,"[('Adagrasib', 0.005, 'uM'), ('LY3200882', 0.5...","((Adagrasib, 0.005), (LY3200882, 0.5))"
54,Adagrasib+LY3200882,0.01+0.5,2,"[('Adagrasib', 0.01, 'uM'), ('LY3200882', 0.5,...","((Adagrasib, 0.01), (LY3200882, 0.5))"
55,Adagrasib+PF-06952229,0.005+0.1,2,"[('Adagrasib', 0.005, 'uM'), ('PF-06952229', 0...","((Adagrasib, 0.005), (PF-06952229, 0.1))"
56,Adagrasib+PF-06952229,0.005+0.5,2,"[('Adagrasib', 0.005, 'uM'), ('PF-06952229', 0...","((Adagrasib, 0.005), (PF-06952229, 0.5))"
57,Adagrasib+PF-06952229,0.01+0.5,2,"[('Adagrasib', 0.01, 'uM'), ('PF-06952229', 0....","((Adagrasib, 0.01), (PF-06952229, 0.5))"
58,Capecitabine+Gemcitabine,0.05+1,2,"[('Gemcitabine', 1.0, 'uM'), ('Capecitabine', ...","((Capecitabine, 0.05), (Gemcitabine, 1.0))"
59,Capecitabine+Gemcitabine,0.5+1,2,"[('Gemcitabine', 1.0, 'uM'), ('Capecitabine', ...","((Capecitabine, 0.5), (Gemcitabine, 1.0))"
60,Capecitabine+Gemcitabine,5+1,2,"[('Capecitabine', 5.0, 'uM'), ('Gemcitabine', ...","((Capecitabine, 5.0), (Gemcitabine, 1.0))"
61,Capecitabine+Oxaliplatin,0.1+0.1,2,"[('Capecitabine', 0.1, 'uM'), ('Oxaliplatin', ...","((Capecitabine, 0.1), (Oxaliplatin, 0.1))"
62,Capecitabine+Oxaliplatin,0.5+0.5,2,"[('Capecitabine', 0.5, 'uM'), ('Oxaliplatin', ...","((Capecitabine, 0.5), (Oxaliplatin, 0.5))"
63,Capecitabine+Oxaliplatin,1+1,2,"[('Capecitabine', 1.0, 'uM'), ('Oxaliplatin', ...","((Capecitabine, 1.0), (Oxaliplatin, 1.0))"
64,Dabrafenib+Trametinib,0.05+0.01,2,"[('Dabrafenib', 0.05, 'uM'), ('Trametinib', 0....","((Dabrafenib, 0.05), (Trametinib, 0.01))"
65,Dabrafenib+Trametinib,0.05+0.05,2,"[('Dabrafenib', 0.05, 'uM'), ('Trametinib', 0....","((Dabrafenib, 0.05), (Trametinib, 0.05))"
66,Dabrafenib+Trametinib,0.05+0.1,2,"[('Dabrafenib', 0.05, 'uM'), ('Trametinib', 0....","((Dabrafenib, 0.05), (Trametinib, 0.1))"
67,Galunisertib+Sotorasib,0.1+0.005,2,"[('Sotorasib', 0.005, 'uM'), ('Galunisertib', ...","((Galunisertib, 0.1), (Sotorasib, 0.005))"
68,Galunisertib+Sotorasib,0.5+0.005,2,"[('Sotorasib', 0.005, 'uM'), ('Galunisertib', ...","((Galunisertib, 0.5), (Sotorasib, 0.005))"
69,Galunisertib+Sotorasib,0.5+0.01,2,"[('Sotorasib', 0.01, 'uM'), ('Galunisertib', 0...","((Galunisertib, 0.5), (Sotorasib, 0.01))"
70,Gemcitabine+Paclitaxel,1+0.05,2,"[('Paclitaxel', 0.05, 'uM'), ('Gemcitabine', 1...","((Gemcitabine, 1.0), (Paclitaxel, 0.05))"
71,Gemcitabine+Paclitaxel,10+0.5,2,"[('Gemcitabine', 10.0, 'uM'), ('Paclitaxel', 0...","((Gemcitabine, 10.0), (Paclitaxel, 0.5))"
72,LY3200882+Sotorasib,0.1+0.005,2,"[('LY3200882', 0.1, 'uM'), ('Sotorasib', 0.005...","((LY3200882, 0.1), (Sotorasib, 0.005))"
73,LY3200882+Sotorasib,0.5+0.005,2,"[('Sotorasib', 0.005, 'uM'), ('LY3200882', 0.5...","((LY3200882, 0.5), (Sotorasib, 0.005))"
74,LY3200882+Sotorasib,0.5+0.01,2,"[('Sotorasib', 0.01, 'uM'), ('LY3200882', 0.5,...","((LY3200882, 0.5), (Sotorasib, 0.01))"
75,PF-06952229+Sotorasib,0.1+0.005,2,"[('PF-06952229', 0.1, 'uM'), ('Sotorasib', 0.0...","((PF-06952229, 0.1), (Sotorasib, 0.005))"
76,PF-06952229+Sotorasib,0.5+0.005,2,"[('PF-06952229', 0.5, 'uM'), ('Sotorasib', 0.0...","((PF-06952229, 0.5), (Sotorasib, 0.005))"
77,PF-06952229+Sotorasib,0.5+0.01,2,"[('PF-06952229', 0.5, 'uM'), ('Sotorasib', 0.0...","((PF-06952229, 0.5), (Sotorasib, 0.01))"
78,RMC-6236+Vociprotafib,0.01+0.001,2,"[('Vociprotafib', 0.001, 'uM'), ('RMC-6236', 0...","((RMC-6236, 0.01), (Vociprotafib, 0.001))"
79,RMC-6236+Vociprotafib,0.01+0.01,2,"[('RMC-6236', 0.01, 'uM'), ('Vociprotafib', 0....","((RMC-6236, 0.01), (Vociprotafib, 0.01))"
80,RMC-6236+Vociprotafib,0.05+0.05,2,"[('Vociprotafib', 0.05, 'uM'), ('RMC-6236', 0....","((RMC-6236, 0.05), (Vociprotafib, 0.05))"
81,Tipiracil+Trifluridine,0.25+0.5,2,"[('Trifluridine', 0.5, 'uM'), ('Tipiracil', 0....","((Tipiracil, 0.25), (Trifluridine, 0.5))"
82,Tipiracil+Trifluridine,2.5+5,2,"[('Tipiracil', 2.5, 'uM'), ('Trifluridine', 5....","((Tipiracil, 2.5), (Trifluridine, 5.0))"
83,Tipiracil+Trifluridine,25+50,2,"[('Tipiracil', 25.0, 'uM'), ('Trifluridine', 5...","((Tipiracil, 25.0), (Trifluridine, 50.0))"
84,Trastuzumab+Tucatinib,0.00068888+0.05,2,"[('Tucatinib', 0.05, 'uM'), ('Trastuzumab', 0....","((Trastuzumab, 0.00068888), (Tucatinib, 0.05))"
85,Trastuzumab+Tucatinib,0.00068888+0.5,2,"[('Tucatinib', 0.5, 'uM'), ('Trastuzumab', 0.0...","((Trastuzumab, 0.00068888), (Tucatinib, 0.5))"
86,Trastuzumab+Tucatinib,0.0034444+5,2,"[('Tucatinib', 5.0, 'uM'), ('Trastuzumab', 0.0...","((Trastuzumab, 0.0034444), (Tucatinib, 5.0))"
87,Fluorouracil+Leucovorin+Oxaliplatin,0.5+0.07+0.015,3,"[('Fluorouracil', 0.5, 'uM'), ('Leucovorin', 0...","((Fluorouracil, 0.5), (Leucovorin, 0.07), (Oxa..."
88,Fluorouracil+Leucovorin+Oxaliplatin,12.5+1.75+0.375,3,"[('Fluorouracil', 12.5, 'uM'), ('Leucovorin', ...","((Fluorouracil, 12.5), (Leucovorin, 1.75), (Ox..."
89,Fluorouracil+Leucovorin+Oxaliplatin,2.5+0.35+0.075,3,"[('Leucovorin', 0.35, 'uM'), ('Oxaliplatin', 0...","((Fluorouracil, 2.5), (Leucovorin, 0.35), (Oxa..."
90,Fluorouracil+Irinotecan+Leucovorin+Oxaliplatin,15+1+2.5+0.5,4,"[('Oxaliplatin', 0.5, 'uM'), ('Fluorouracil', ...","((Fluorouracil, 15.0), (Irinotecan, 1.0), (Leu..."
91,Fluorouracil+Irinotecan+Leucovorin+Oxaliplatin,30+2+5+1,4,"[('Oxaliplatin', 1.0, 'uM'), ('Irinotecan', 2....","((Fluorouracil, 30.0), (Irinotecan, 2.0), (Leu..."
92,Fluorouracil+Irinotecan+Leucovorin+Oxaliplatin,60+4+10+2,4,"[('Oxaliplatin', 2.0, 'uM'), ('Fluorouracil', ...","((Fluorouracil, 60.0), (Irinotecan, 4.0), (Leu..."

## combo vs. monotherapies

In [4]:
# Combination therapies vs. their single-agent (monotherapy) arms.
# One row per unique combo condition (47). For each: which component drugs were
# also run alone, at exactly which dose, and the full mono dose ladder available.
#
# status tells you whether the Bliss additive null -- sum of single-agent log2
# growth ratios, since sensitivity is already log2(P_treated / P_control) -- is
#   complete     directly computable at the matched doses
#   dose gap     every component HAS a mono arm, but not at this dose (interpolatable)
#   no mono arm  >=1 component was never run alone at any dose (not recoverable)
g = lambda v: f"{v:g}"

mono_pairs = {t[0] for t in singles.parsed}          # (drug, dose) run as a single agent
ladder = defaultdict(list)                           # drug -> sorted mono dose ladder
for t in singles.parsed:
    drug, dose = t[0]
    ladder[drug].append(dose)
ladder = {k: sorted(v) for k, v in ladder.items()}
moa_of = dict(zip(drug_md_df.drug, drug_md_df["moa-fine"]))

def status_of(comps):
    if all((dr, ds) in mono_pairs for dr, ds in comps): return "complete"
    if all(dr in ladder for dr, _ in comps):            return "dose gap"
    return "no mono arm"

combo_tbl = pd.DataFrame([dict(
    combo  = r.drugs,
    dose   = r.doses,
    n      = r.n_drugs,
    moa    = " + ".join(dict.fromkeys(moa_of.get(dr, "?") for dr, _ in r.parsed)),
    status = status_of(r.parsed),
    # component drugs that exist as a single arm at *any* dose ([] if none)
    single_arms     = [dr for dr, _ in r.parsed if dr in ladder],
    # components whose exact (drug, dose) was also run alone ([] if none)
    exact_matches   = [f"{dr} @ {g(ds)}" for dr, ds in r.parsed if (dr, ds) in mono_pairs],
    # every dose each component was measured at as a single agent ("--" if never)
    available_doses = " | ".join(
        f"{dr}: {', '.join(g(x) for x in ladder[dr])}" if dr in ladder else f"{dr}: --"
        for dr, _ in r.parsed),
) for r in combos.itertuples()])

rank = {"complete": 0, "dose gap": 1, "no mono arm": 2}
combo_tbl = (combo_tbl.assign(_r=combo_tbl.status.map(rank))
             .sort_values(["_r", "combo", "dose"])
             .drop(columns="_r").reset_index(drop=True))

n_cells = summary_stats_df.groupby("condition").cell_line.nunique()
orphans = sorted({dr for t in combos.parsed for dr, _ in t} - set(ladder))
print(f"{len(combo_tbl)} combo conditions | {combos.drugs.nunique()} distinct drug sets | "
      f"{len(singles)} single-agent conditions over {len(ladder)} drugs")
print(f"every condition measured in {n_cells.min()}-{n_cells.max()} cell lines "
      f"(= n available to fit a per-combo interaction term)")
print(combo_tbl.status.value_counts().reindex(rank).to_string())
print(f"\nappear ONLY in combos, never alone ({len(orphans)}): {', '.join(orphans)}")

(combo_tbl.style
   .set_caption("EmeraldBay combination therapies and their single-agent coverage")
   .apply(lambda c: [{"complete":    "background-color:#d8f0dc",
                      "dose gap":    "background-color:#fdf2cf",
                      "no mono arm": "background-color:#fadbd8"}.get(v, "") for v in c],
          subset=["status"])
   .set_properties(subset=["available_doses", "moa"], **{"font-size": "90%"})
   .hide(axis="index"))

47 combo conditions | 16 distinct drug sets | 44 single-agent conditions over 19 drugs
every condition measured in 52-52 cell lines (= n available to fit a per-combo interaction term)
status
complete       17
dose gap        9
no mono arm    21

appear ONLY in combos, never alone (8): Dabrafenib, Leucovorin, PF-06952229, Tipiracil, Trametinib, Trastuzumab, Trifluridine, Tucatinib

# Adding mechanism classes

In [7]:
# Pharmacological design class for every combination condition (47 rows / 16 drug sets).
# This is the a-priori class -- the relationship the components were *designed* to have --
# so it comes from metadata alone and needs no growth or expression data. Use it as the
# label; derive the measured-interaction classes (synergy, transcriptional geometry)
# separately and cross-tab against it.
#
#   same-node redundancy               components converge on one protein / cascade node
#   vertical blockade                  different nodes of the SAME cascade
#   horizontal bypass                  two distinct pathways
#   same process / different mechanism  all cytotoxic, all DNA-directed, different mechanisms
#   orthogonal process                 cytotoxics acting on unrelated cell processes
#   pharmacokinetic modulation         one antiproliferative agent + partner(s) that only boost its exposure
#
# Rule-based rather than hand-labelled so every call is auditable via `basis` and so
# combos added later classify themselves. Two lookups are needed beyond drug_md_df,
# because neither distinction exists in its columns: PATHWAY places each signalling drug
# on a (pathway, cascade node), since moa-fine calls both RAF and TGFBR1 drugs kinase
# inhibitors and so cannot separate "same cascade" from "different cascade"; PROCESS gives
# each cytotoxic the process it acts on, since Gemcitabine, Oxaliplatin and Leucovorin all
# carry targets == "none" under one shared moa-fine string.

PATHWAY = {                                   # drug -> (pathway, cascade node)
    "Cetuximab": ("MAPK", "EGFR"), "Panitumumab": ("MAPK", "EGFR"),
    "Lapatinib ditosylate": ("MAPK", "EGFR/ERBB2"),
    "Trastuzumab": ("MAPK", "ERBB2"), "Pertuzumab": ("MAPK", "ERBB2"),
    "Tucatinib": ("MAPK", "ERBB2"),
    "Vociprotafib": ("MAPK", "SHP2"),
    "Adagrasib": ("MAPK", "RAS"), "Sotorasib": ("MAPK", "RAS"),
    "GDC-6036": ("MAPK", "RAS"), "RMC-6236": ("MAPK", "RAS"),
    "Dabrafenib": ("MAPK", "RAF"), "Encorafenib": ("MAPK", "RAF"),
    "Regorafenib": ("MAPK", "RAF"), "Trametinib": ("MAPK", "MEK"),
    "Galunisertib": ("TGFB", "TGFBR1"), "LY3200882": ("TGFB", "TGFBR1"),
    "PF-06952229": ("TGFB", "TGFBR1"),
}
CASCADE = ["EGFR", "ERBB2", "EGFR/ERBB2", "SHP2", "RAS", "RAF", "MEK", "TGFBR1"]

PROCESS = {                                   # cytotoxic -> process acted on
    "Capecitabine": "antimetabolite/TYMS", "Fluorouracil": "antimetabolite/TYMS",
    "Trifluridine": "antimetabolite/TYMS", "Tipiracil": "TYMP inhibition (PK)",
    "Gemcitabine": "antimetabolite/dNTP",  "Leucovorin": "folate modulation",
    "Oxaliplatin": "DNA crosslink",        "Irinotecan": "TOP1 poison",
    "Paclitaxel": "microtubule",
}
DNA_DIRECTED = {"antimetabolite/TYMS", "antimetabolite/dNTP", "folate modulation",
                "DNA crosslink", "TOP1 poison"}

# Partners that are not cytotoxic alone and are dosed to modulate the other agent:
# Leucovorin stabilises the 5-FU/TYMS ternary complex, Tipiracil blocks TYMP-mediated
# degradation of trifluridine (which is why Tipiracil's PROCESS entry is TYMP inhibition,
# not a second TYMS antimetabolite). An additive null is wrong by construction for these
# -- sub-additivity is the expected result, not a finding. Handled two ways below: a combo
# that is a single antiproliferative agent + only modulator partner(s) gets its own
# "pharmacokinetic modulation" class (design_class step 0); a modulator riding along in a
# larger multi-cytotoxic regimen (Leucovorin in FOLFOX/FOLFIRINOX) keeps the regimen's
# class but is surfaced in the modulator_partner column.
MODULATOR = {"Leucovorin", "Tipiracil"}

_tgt_md = dict(zip(drug_md_df.drug, drug_md_df.targets))

def _targets(drug):
    return {t.strip() for t in str(_tgt_md.get(drug) or "").split(",")
            if t.strip() not in ("", "none", "nan")}

def design_class(comps):
    """(class, basis) for one parsed condition -- a tuple of (drug, dose) pairs."""
    drugs = [dr for dr, _ in comps]
    tgt   = {dr: _targets(dr) for dr in drugs}
    node  = {dr: PATHWAY[dr][1] for dr in drugs if dr in PATHWAY}
    paths = {PATHWAY[dr][0] for dr in drugs if dr in PATHWAY}

    # 0. pure modulator partners -- strip them; if a single antiproliferative agent
    # remains, the combo exists to raise that agent's exposure, not to combine two
    # mechanisms (see MODULATOR). Runs first so the shared-target check below can't
    # mislabel e.g. Tipiracil+Trifluridine as redundancy on their shared TYMS annotation.
    core = [dr for dr in drugs if dr not in MODULATOR]
    if MODULATOR.intersection(drugs) and len(core) == 1:
        mods = ", ".join(sorted(MODULATOR.intersection(drugs)))
        return "pharmacokinetic modulation", f"{core[0]} boosted by {mods}"

    # 1. any two components converging on one protein or one cascade node
    for i, a in enumerate(drugs):
        for b in drugs[i + 1:]:
            shared = tgt[a] & tgt[b]
            if shared:
                return "same-node redundancy", f"shared target: {', '.join(sorted(shared))}"
            if a in node and node[a] == node.get(b):
                return "same-node redundancy", f"shared node: {node[a]}"

    # 2/3. every component is a signalling drug -> one cascade, or more than one
    if len(node) == len(drugs):
        ordered = sorted(set(node.values()), key=CASCADE.index)
        if len(paths) == 1:
            return "vertical blockade", f"{paths.pop()}: {' -> '.join(ordered)}"
        return "horizontal bypass", f"{' + '.join(sorted(paths))}: {' + '.join(ordered)}"

    # 4/5. every component is a cytotoxic -> all DNA-directed, or not
    if all(dr in PROCESS for dr in drugs):
        procs = {PROCESS[dr] for dr in drugs}
        basis = " + ".join(sorted(procs))
        return (("same process / different mechanism", basis) if procs <= DNA_DIRECTED
                else ("orthogonal process", basis))

    return "unclassified", ""

_rows = []
for r in combos.itertuples():
    cls, basis = design_class(r.parsed)
    _rows.append(dict(
        condition    = r.condition,      # raw key -- joins straight onto summary_stats_df
        drugs        = r.drugs,
        doses_uM     = r.doses,
        n_drugs      = r.n_drugs,
        design_class = cls,
        basis        = basis,
        modulator_partner = "; ".join(dr for dr, _ in r.parsed if dr in MODULATOR),
        moa          = " + ".join(dict.fromkeys(moa_of.get(dr, "?") for dr, _ in r.parsed)),
        _dose_key    = tuple(c for _, c in r.parsed),
    ))
combo_class = pd.DataFrame(_rows)

# dose_level: 1 = lowest dose combination measured for that drug set. Ranks the numeric
# dose tuple, not the doses string, so "10" doesn't sort below "5".
combo_class["dose_level"] = (combo_class.groupby("drugs")._dose_key
                             .rank(method="dense").astype(int))
combo_class = (combo_class.drop(columns="_dose_key")
               .sort_values(["design_class", "drugs", "dose_level"])
               .reset_index(drop=True)
               [["condition", "drugs", "doses_uM", "dose_level", "n_drugs",
                 "design_class", "basis", "modulator_partner", "moa"]])

assert len(combo_class) == len(combos), "lost a combo condition"
assert (combo_class.design_class != "unclassified").all(), (
    "unclassified: "
    f"{combo_class.loc[combo_class.design_class == 'unclassified', 'drugs'].unique()}")

print(f"{len(combo_class)} combo conditions | {combo_class.drugs.nunique()} drug sets "
      f"| {combo_class.design_class.nunique()} design classes")
print(combo_class.groupby("design_class")
      .agg(conditions=("condition", "size"), drug_sets=("drugs", "nunique")).to_string())

_PALETTE = {"same-node redundancy":              "background-color:#e8dff5",
            "vertical blockade":                 "background-color:#d8f0dc",
            "horizontal bypass":                 "background-color:#d6eaf8",
            "same process / different mechanism": "background-color:#fdf2cf",
            "orthogonal process":                "background-color:#fadbd8",
            "pharmacokinetic modulation":        "background-color:#e6d5c3"}
(combo_class.style
   .set_caption("EmeraldBay combination conditions by pharmacological design class")
   .apply(lambda c: [_PALETTE.get(v, "") for v in c], subset=["design_class"])
   .set_properties(subset=["condition"], **{"font-size": "80%"})
   .set_properties(subset=["basis", "moa"], **{"font-size": "90%"})
   .hide(axis="index"))

47 combo conditions | 16 drug sets | 6 design classes
                                    conditions  drug_sets
design_class
horizontal bypass                           18          6
orthogonal process                           2          1
pharmacokinetic modulation                   3          1
same process / different mechanism          12          4
same-node redundancy                         3          1
vertical blockade                            9          3

In [ ]:
# Save the condition -> design-class map next to the other EmeraldBay artifacts.
# `condition` is the verbatim summary_statistics key, so downstream work can
# pd.merge(summary_stats_df, combo_class, on="condition") and get 52 cell lines x
# 47 combo conditions labelled by design class with no re-parsing.
from pathlib import Path

repo_root = next(p for p in [Path.cwd(), *Path.cwd().parents]
                 if (p / "pyproject.toml").exists())
out_path = repo_root / "artifacts" / "emeraldbay_combo_design_classes.csv"
out_path.parent.mkdir(exist_ok=True)
combo_class.to_csv(out_path, index=False)
print(f"wrote {len(combo_class)} rows x {combo_class.shape[1]} cols -> "
      f"{out_path.relative_to(repo_root)}")

# round-trip check: the file reads back identical to what is in memory
pd.testing.assert_frame_equal(pd.read_csv(out_path).fillna(""),
                              combo_class.fillna(""), check_dtype=False)
print("round-trip OK")